### ISSUE TITLE
Error while running in dev config

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat-aem-integration-tests#1]

**Comment by DeChrish** [comment]
`-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[8143]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running com.cognifide.bdd.demo.suite.BbAemTouchUiSuite
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.156 sec <<< FAILURE! - in com.cognifide.bdd.demo.suite.BbAemTouchUiSuite
initializationError(com.cognifide.bdd.demo.suite.BbAemTouchUiSuite)  Time elapsed: 0.015 sec  <<< ERROR!
com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 52264
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:712)
	at com.google.inject.internal.Errors.formatSource(Errors.java:684)
	at com.google.inject.internal.Errors.format(Errors.java:555)
	at com.google.inject.CreationException.getMessage(CreationException.java:48)
	at org.apache.maven.surefire.report.SmartStackTraceParser.toString(SmartStackTraceParser.java:308)
	at org.apache.maven.surefire.report.SmartStackTraceParser.innerMostWithFocusOnClass(SmartStackTraceParser.java:246)
	at org.apache.maven.surefire.common.junit4.JUnit4StackTraceWriter.writeTrimmedTraceToString(JUnit4StackTraceWriter.java:97)
	at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:330)
	at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:312)`
